/* Future Ready AI — final header/contact patch
   IMPORTANT: every header uses the exact same approved group image. */
(function(){
  const LOCKED_IMAGE='assets/images/future-ready-ai-approved-group.png';
  const CALENDLY='https://calendly.com/andrea-maisonglamouretgrace/discovery-call';
  const EMAIL='andrea@maisonglamouretgrace.com';
  const SITE='https://www.maisonglamouretgrace.com/';
  const pages={
    'index.html':{theme:'home',eyebrow:'K–12 AI Literacy · Real-World Skills · Brighter Futures',title:'Helping Students Understand, Create, and Lead with AI',sub:'A connected K–12 AI literacy pathway that builds confidence, creativity, responsible use, and future-ready skills.',primary:['Explore the Curriculum','curriculum.html'],secondary:['Watch Video','#future-ready-guide'],micro:['Grade Band Pathways','Real-World Learning','Career-Connected Skills']},
    '':{theme:'home',eyebrow:'K–12 AI Literacy · Real-World Skills · Brighter Futures',title:'Helping Students Understand, Create, and Lead with AI',sub:'A connected K–12 AI literacy pathway that builds confidence, creativity, responsible use, and future-ready skills.',primary:['Explore the Curriculum','curriculum.html'],secondary:['Watch Video','#future-ready-guide'],micro:['Grade Band Pathways','Real-World Learning','Career-Connected Skills']},
    'about.html':{theme:'about',eyebrow:'Purpose · People · Responsible AI',title:'Building Future-Ready Learners Through Human-Centered AI Education',sub:'Future Ready AI helps learners and educators understand AI, use it responsibly, and apply human judgment, creativity, and curiosity to real-world learning.',primary:['Explore the Curriculum','curriculum.html'],secondary:['Meet the Founder','#founder'],micro:['Human-Centered','Responsible AI','Future Readiness']},
    'curriculum.html':{theme:'curriculum',eyebrow:'A Connected K–12 AI Literacy Pathway',title:'A Complete Curriculum for Every Stage of Learning',sub:'Three grade-band pathways build foundational AI knowledge and real-world skills through hands-on projects, ethical exploration, and career-connected learning.',primary:['Explore the Curriculum','#grade-bands'],secondary:['View Sample Lessons','#sample-lessons'],micro:['Elementary Grades 3–5','Middle School Grades 6–8','High School Grades 9–12']},
    'educators.html':{theme:'educators',eyebrow:'Practical Tools · Professional Learning · Lasting Impact',title:'Empowering Educators to Bring AI to Life',sub:'Get the guides, lesson supports, and professional learning you need to confidently teach AI literacy in real classrooms.',primary:['Explore Educator Resources','resources.html'],secondary:['View Professional Learning','#professional-learning'],micro:['Implementation Guides','Lesson Plans & Slide Decks','PD Workshops & On-Demand Training']},
    'schools.html':{theme:'schools',eyebrow:'School-Wide Solutions · Equitable Access · Measurable Impact',title:'Prepare All Students for an AI-Powered Future',sub:'Partner with us to bring a cohesive, research-aligned AI literacy program to your school or district with a scalable, supported implementation model.',primary:['Partner with Us','contact.html'],secondary:['Learn More','#implementation'],micro:['Scalable Implementation','Equity-Focused Design','Ongoing Support']},
    'resources.html':{theme:'resources',eyebrow:'Ideas · Insights · Tools · In Action',title:'Resources to Keep You Moving Forward',sub:'Explore curated resources, practical tools, and real-world examples to help you bring AI to life in your classroom, school, or district.',primary:['Explore Resources','#resource-library'],secondary:['View Featured Content','#featured'],micro:['Articles & Insights','Videos & Webinars','Tools & Templates']},
    'contact.html':{theme:'contact',eyebrow:'Future Ready AI',title:'Let’s Talk About Bringing Future Ready AI to Your Learners.',sub:'We partner with schools, districts, educators, and community organizations to deliver AI literacy, educator learning, and future-ready experiences that build confidence, creativity, and real-world skills.',primary:['Book a Discovery Call',CALENDLY,true],secondary:['Send a Program Inquiry','#inquiry-form'],micro:['Schools & Districts','Educators','Community Programs']}
  };
  function key(){return location.pathname.split('/').pop()||'index.html';}
  function linkHTML(item,kind){const ext=item[2]?' target="_blank" rel="noopener noreferrer"':'';return `<a class="fra-hero__btn fra-hero__btn--${kind}" href="${item[1]}"${ext}>${item[0]} →</a>`;}
  function buildHero(cfg){
    return `<section class="fra-hero fra-theme-${cfg.theme}" aria-label="${cfg.title}"><div class="fra-hero__inner"><div class="fra-hero__copy"><p class="fra-hero__eyebrow">${cfg.eyebrow}</p><h1>${cfg.title}</h1><p class="fra-hero__sub">${cfg.sub}</p><div class="fra-hero__actions">${linkHTML(cfg.primary,'solid')}${linkHTML(cfg.secondary,'outline')}</div><div class="fra-hero__micro">${cfg.micro.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="fra-hero__visual"><img src="${LOCKED_IMAGE}" alt="Future Ready AI founder Andrea Davis-Baptiste with the approved student puppet characters and learning robot" fetchpriority="high"/></div></div></section>`;
  }
  function initHero(){const cfg=pages[key()]||pages['index.html'];const old=document.querySelector('.approved-hero');if(!old)return;old.outerHTML=buildHero(cfg);}
  function initContact(){if(key()!=='contact.html')return;const section=document.querySelector('#inquiry-form');if(!section)return;const container=section.querySelector('.container');const form=container?.querySelector('form');if(!container||!form)return;
    form.removeAttribute('data-demo-form');
    const wrap=document.createElement('div');wrap.className='fra-contact-shell';
    const left=document.createElement('div');left.className='fra-contact-form';left.innerHTML='<p class="eyebrow">Program Inquiry</p><h2>Send a Program Inquiry</h2><p>Tell us about your organization and how we can support your learners. We’ll follow up within 2–3 business days.</p>';left.appendChild(form);
    const side=document.createElement('aside');side.className='fra-contact-side';side.innerHTML=`<section class="fra-contact-card"><p class="eyebrow">Discovery Call</p><h2>Book a Discovery Call</h2><p>Schedule a 30-minute conversation to discuss your goals, ask questions, and explore how Future Ready AI can support your learners.</p><div class="fra-contact-name"><img src="assets/images/founder-andrea-davis-baptiste.jpg" alt="Andrea Davis-Baptiste"><div><strong>Andrea Davis-Baptiste</strong><span>Founder & Program Lead · 30 min · Google Meet or phone</span></div></div><a class="fra-calendly-btn" href="${CALENDLY}" target="_blank" rel="noopener noreferrer">Select a Date & Time →</a></section><section class="fra-contact-card fra-contact-card--blue"><p class="eyebrow">Direct Contact</p><h2>Future Ready AI</h2><p><a href="mailto:${EMAIL}">${EMAIL}</a></p><p><a href="${SITE}" target="_blank" rel="noopener noreferrer">maisonglamouretgrace.com ↗</a></p></section>`;
    container.replaceWith(wrap);wrap.append(left,side);
    form.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();if(!form.checkValidity()){form.reportValidity();return;}const d=new FormData(form);const subject='Future Ready AI Program Inquiry — '+(d.get('organization')||d.get('name')||'New Inquiry');const body=[`Name: ${d.get('name')||''}`,`Organization: ${d.get('organization')||''}`,`Role: ${d.get('role')||''}`,`Email: ${d.get('email')||''}`,`Phone: ${d.get('phone')||''}`,`Inquiry Type: ${d.get('inquiry_type')||''}`,`Grade Levels: ${d.get('grades')||''}`,`Learners/Educators: ${d.get('size')||''}`,'','Message:',d.get('message')||''].join('\n');location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;},true);
  }
  document.addEventListener('DOMContentLoaded',()=>{initContact();});
})();
